### PR TITLE
Bump to 4.1.1.0 and add changelogs

### PR DESCRIPTION
**Pull request by cdepillabout**

### CODE REVIEW

**Comment by cdepillabout** [comment]
@georgefst @juhp Released to hackage as https://hackage.haskell.org/package/pretty-simple-4.1.1.0

**Comment by juhp** [comment]
Cool

**Comment by georgefst** [comment]
Shouldn't this have been a major bump? We've changed the behaviour of a function (albeit in a way that seems very _unlikely_ to actually break any upstream code).

**Comment by georgefst** [comment]
Actually, maybe golden test failures (even though for golden tests, you probably wouldn't use compact mode)...

**Comment by cdepillabout** [comment]
Ah, good point.  I could see this breaking some golden tests.

You want me to deprecate 4.1.1.0 on Hackage and release 4.2.0.0 instead?  Or, we could just wait for someone to complain about it.

**Pull request merged**
