### PR TITLE
Make newlines when layer has another layer + tests

### LINKED ISSUE #17: make more newlines in the output
The output is pretty hard to read when there are not enough newlines.

bad-formatting

Everything after `TypeDeclaration` should really have newlines.

### PR DESCRIPTION
**Pull request by andrew-lei**
Fixes #17

### CODE REVIEW

**Comment by cdepillabout** [comment]
This looks good to me, thanks again!

You've sent quite a few really nice PRs the past couple weeks.  I really appreciate your help.

Would you be interested in being a co-maintainer for `pretty-simple`?  If so, you could help look at PRs, merge things in, make releases, etc.  I can make you a maintainer here on Github, and then you'll have to give me your username on Hackage so I can add you as a maintainer there as well.

At some point, I would like to rewrite both the parsing and pretty-printing code (#16 and #25).  However, I haven't really had enough time to devote to this.  I don't think it should be that difficult, it will just take time to sit down and do.  Once that is finished, it should be much easier to knock off the remaining open issues.

**Comment by andrew-lei** [comment]
Thanks! And I'd be happy to. I don't have an account on Hackage yet, but I can create one if you want.

I was actually looking at the lexer/parser issue and the laziness. I'll see if I can come up with anything in the next couple of days.

**Comment by cdepillabout** [comment]
> I don't have an account on Hackage yet, but I can create one if you want.

Thanks, that would be a big help.  Once you let me know your Hackage ID, I'll add you as a maintainer here on Github.  Then you can go ahead and merge this in yourself and make a release.

> I was actually looking at the lexer/parser issue and the laziness. I'll see if I can come up with anything in the next couple of days.

That sounds great.  My explanations in #16 and #25 are pretty short, so let me know if you have any questions!

**Comment by andrew-lei** [comment]
OK. Username andrewlei

**Comment by cdepillabout** [comment]
Thanks for merging this in.

Feel free to make a release of `pretty-simple` to Hackage.  In case you haven't uploaded packages to Hackage before, I created a quick [checklist](https://functor.tokyo/blog/2018-07-16-release-haskell-packages-to-hackage) on the steps to perform.  If you find anything poorly explained or hard to understand, definitely let me know!

**Pull request merged**
