### PR TITLE
Fix handling of Char literals

### LINKED ISSUE #45: the parser doesn't understand Haskell characters like 'a'
```
Text.Pretty.Simple> pStringNoColor "[']']"
"[ ' ]'"
```

The correct output should be `"[']'"`.

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #45.

### CODE REVIEW

**Comment by cdepillabout** [comment]
I only did a quick skim over this, but it looks pretty good!  Give me a week or so to do a thorough review of this.

**Comment by cdepillabout** [comment]
@sjakobi Sorry for making you wait for this.

In 0b95aec I added some tests and fixed up a small problem with parsing other characters.

**Comment by cdepillabout** [comment]
Bumped version and released to hackage:

https://hackage.haskell.org/package/pretty-simple-3.2.0.0

**Comment by sjakobi** [comment]
No worries and many thanks! :)

**Pull request merged**
