### PR TITLE
Lazy parser

### LINKED ISSUE #9: parser/printer could be more lazy (to handle prefix of infinite stream)
Just an idea. It seems that the input is evaluated fully, before any output appears.

Try `pPrint $ repeat (False,())` which shows nothing, while `show $ repeat (False,())` will produce output.

At least in a ghci session it's nice to see prefixes of (potentially) infinite streams appear as the are computed, as in `filter (\q -> show q == reverse(show q)) $ map (^2) [1..]` or whatever.

Now I see that is a challenge for the parser (it wants nested parentheses, so it will wait
for the closing one always?) and for the printer (layout combinators may be strict as well).

### PR DESCRIPTION
**Pull request by andrew-lei**
Closes #9.

### CODE REVIEW

**Comment by andrew-lei** [comment]
Figured out how to rerun the job. Looks like it was just bad luck.

**Comment by cdepillabout** [comment]
Thanks again for implementing this!  The code looks great.

Also thanks for investigating the travis job.

You want to go ahead and remove the containers and parsec dependencies, update the version number, and [make a release](https://functor.tokyo/blog/2018-07-16-release-haskell-packages-to-hackage)? (If not, no problem, I can always do it.)

I don't think this PR changes the types of any user-facing functions, so we could probably just update the minor version number.  However, this lazy functionality is really great, and a big change to pretty-simple, so I'd even be fine with making the version something like 3.0.0.0.  (I'd also like to make a blog post introducing this new version of pretty-simple, so it would sound better if it was bumped to 3.0.0.0, however this is a bad reason to decide the version of library!)

**Comment by cdepillabout** [comment]
Also, this is from https://github.com/cdepillabout/pretty-simple/issues/9#issuecomment-410939554:

> As I've mentioned, I think it would work well as part of a post-processing step that would allow a user to perform more general sorts of manipulation on the intermediate bits. So the post-processor should be a function either [Output] -> [Output] or [Expr] -> [Expr]. I'm leaning towards the latter because I think it would allow for more general manipulation of the structure (for instance, to hide everything in certain Parens).
>
> I was thinking one way to do this would be to perhaps have a constructor that contains the parsed value and either the type information (string literal, number, datetime, etc.) or the colour.

Did you want to create a new issue about this?  Unless you're planning on doing this right away, it might help someone else looking to implement this.

**Comment by cdepillabout** [comment]
Sorry, one more thing.  I just opened #38 adding a test that unicode is printed out correctly.

Could you either merge that into this PR, or just merge #38 into master after merging this PR?

**Comment by andrew-lei** [comment]
OK. I have bumped the version number to 2.2.0.0 and updated the changelog. I will open up that comment as another issue and I will merge as soon as Travis has finished.

**Comment by andrew-lei** [comment]
OK, I managed to upload it to Hackage. The documentation isn't appearing, though, but I'm assuming that it takes a moment to generate?

**Comment by cdepillabout** [comment]
@andrew-lei Thanks a lot for uploading this to Hackage!

The documentation usually takes a while to appear.  It looks like has been created:

http://hackage.haskell.org/package/pretty-simple

Also, in the future, when you make a release, would you be able to create a tag and push it to github?  I'll go ahead and run the following commands at the current master branch:

```sh
$ git tag v2.2.0.0 -m 'release version 2.2.0.0'
$ git push --tag
```

**Pull request merged**
