### PR TITLE
Remove trailing whitespaces from the end of lines

### PR DESCRIPTION
**Pull request by ghallak**
Closes: #61

### CODE REVIEW

**Comment by cdepillabout** [comment]
@ghallak Thanks for trying to fix this.

It looks like CI is now failing on some of the doctests with this improvement.  Could you fix these up?

https://travis-ci.org/cdepillabout/pretty-simple/jobs/641713245#L468

**Comment by ghallak** [comment]
I have fixed the doctests expectations and squashed the commits. The CI checks are passing now.

**Comment by cdepillabout** [comment]
Looks good to me.  Thanks!

**Comment by cdepillabout** [comment]
@ghallak I wasn't planning on creating a Hackage release for this feature, but if you'd like one, please let me know!

**Comment by ghallak** [comment]
I think it's fine without a Hackage release for this feature, the fixed issue was not causing the biggest problems.

**Comment by asr** [comment]
I would appreciate a Hackage release including this feature.

**Comment by cdepillabout** [comment]
No problem, released `pretty-simple-3.2.2.0`:

https://hackage.haskell.org/package/pretty-simple-3.2.2.0

**Comment by asr** [comment]
Great! Thanks!

**Pull request merged**
